### ISSUE TITLE
I don't know how to run it

### ISSUE THREAD

**Issue by Dark-Ale27** [1fge/open-supreme#14]
After that I do:   python osp.py, it says:
 File "/Users/alessandromaniscalco/PycharmProjects/open-supreme/osp.py", line 184, in <module>
    start_captcha_server()
  File "/Users/alessandromaniscalco/PycharmProjects/open-supreme/osp.py", line 180, in start_captcha_server
    harvester.launch_browser()
  File "/Users/alessandromaniscalco/PycharmProjects/open-supreme/venv/lib/python3.9/site-packages/harvester/server/__init__.py", line 213, in launch_browser
    return browserModule.launch(list(self.domain_cache.keys()),
  File "/Users/alessandromaniscalco/PycharmProjects/open-supreme/venv/lib/python3.9/site-packages/harvester/browser.py", line 108, in launch
    binary_location = get_browser_binary_location(browser)
  File "/Users/alessandromaniscalco/PycharmProjects/open-supreme/venv/lib/python3.9/site-packages/harvester/browser.py", line 83, in get_browser_binary_location
    return registry.get(platform.system())[browser]()
  File "/Users/alessandromaniscalco/PycharmProjects/open-supreme/venv/lib/python3.9/site-packages/harvester/browser.py", line 39, in read_osx_defults
    binary_path = plistlib.readPlist(

Why PLEASE help me

**Comment by 1fge** [comment]
Hi, do you have Chrome browser installed? I believe that one of the dependencies for the project requires Chrome browser, so if this fixes your problem I will update the README making a note of this. 

EDIT: Can confirm that you need Chrome installed in order for the captcha harvester to work. I'll go ahead and add that to the installation notes. Thanks for bringing this up!

**Comment by Dark-Ale27** [comment]
It starts working (can write Profiles and Tasks) when I comment out in osp.py #harvester.launch_browser()
This is what happens:
Main Menu
0: Profiles
1: Tasks
2: Open-Supreme

> 2
Open Supreme

run: Start Tasks
1: Main Menu

> run
Pants: Searching for ['Logo', 'Rib', 'Work']
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Users/alessandromaniscalco/Desktop/open-supreme/opensupreme/run_tasks.py", line 46, in run
    run_task(
  File "/Users/alessandromaniscalco/Desktop/open-supreme/opensupreme/run_tasks.py", line 111, in run_task
    item_id, size_id, style_id, atc_chk = return_item_ids(session, positive_keywords, negative_keywords, category, size, color, task_name, screenlock)
  File "/Users/alessandromaniscalco/Desktop/open-supreme/opensupreme/look_for_stock.py", line 65, in return_item_ids
    
  File "/Users/alessandromaniscalco/Desktop/open-supreme/opensupreme/look_for_stock.py", line 53, in retrieve_style_ids
    
  File "/Users/alessandromaniscalco/Desktop/open-supreme/opensupreme/look_for_stock.py", line 200, in parse_for_styles
    Get all of the different styles and colors for a specific item.
KeyError: 'chk'


When I don't comment out #harvester.launch_browser(), this is what happens:

 File "/Users/alessandromaniscalco/Desktop/open-supreme/osp.py", line 184, in <module>
    start_captcha_server()
  File "/Users/alessandromaniscalco/Desktop/open-supreme/osp.py", line 180, in start_captcha_server
    harvester.launch_browser()
  File "/Users/alessandromaniscalco/Desktop/open-supreme/venv/lib/python3.9/site-packages/harvester/server/__init__.py", line 213, in launch_browser
    return browserModule.launch(list(self.domain_cache.keys()),
  File "/Users/alessandromaniscalco/Desktop/open-supreme/venv/lib/python3.9/site-packages/harvester/browser.py", line 108, in launch
    binary_location = get_browser_binary_location(browser)
  File "/Users/alessandromaniscalco/Desktop/open-supreme/venv/lib/python3.9/site-packages/harvester/browser.py", line 83, in get_browser_binary_location
    return registry.get(platform.system())[browser]()
  File "/Users/alessandromaniscalco/Desktop/open-supreme/venv/lib/python3.9/site-packages/harvester/browser.py", line 39, in read_osx_defults
    binary_path = plistlib.readPlist(
AttributeError: module 'plistlib' has no attribute 'readPlist'
**I think that there is a problem with the module plistlib in python 3.9**

**Comment by 1fge** [comment]
Yep. It looks like the `readPlist` function was removed in Python 3.9 so that's why it's running into issues. I created a PR for the CaptchaHarvester repository so hopefully that can be integrated soon.

**Comment by 1fge** [comment]
Thanks for bringing this issue up. Going to be closing it now as it all seems resolved, but create another issue if you encounter any other problems.

 If anyone reading this in the future has this problem, you may need to manually clone and install the CaptchaHarvester repository to get the library working on Mac.
