### ISSUE TITLE
Harvester library - old

### ISSUE THREAD

**Issue by makovez** [1fge/open-supreme#20]
This library is very old and it doesen't work on my lxde linux system.

>namoso@namoso-hpelitebook2570p:~/open-supreme$ python osp.py 
Traceback (most recent call last):
  File "osp.py", line 174, in <module>
    start_captcha_server()
  File "osp.py", line 171, in start_captcha_server
    harvester.launch_browser()
  File "/home/namoso/.local/lib/python3.8/site-packages/harvester/server/__init__.py", line 213, in launch_browser
    return browserModule.launch(list(self.domain_cache.keys()),
  File "/home/namoso/.local/lib/python3.8/site-packages/harvester/browser.py", line 108, in launch
    binary_location = get_browser_binary_location(browser)
  File "/home/namoso/.local/lib/python3.8/site-packages/harvester/browser.py", line 83, in get_browser_binary_location
    return registry.get(platform.system())[browser]()
TypeError: 'NoneType' object is not subscriptable

**Comment by 1fge** [comment]
The CaptchaHarvester repository states that it doesn't currently work with Linux.
