### ISSUE TITLE
harverster.launch_browser() incorrectly work

### ISSUE THREAD

**Issue by Alymbekov** [1fge/open-supreme#21]
When i run python3 osp.py i got error 

````
Traceback (most recent call last):
  File "http://osp.py", line 173, in <module>
    start_captcha_server()
  File "http://osp.py", line 170, in start_captcha_server
    harvester.launch_browser()
  File "open-supreme/env/lib/python3.8/site-packages/harvester/server/__init__.py", line 213, in launch_browser
    return browserModule.launch(list(self.domain_cache.keys()),
  File "open-supreme/env/lib/python3.8/site-packages/harvester/browser.py", line 108, in launch
    binary_location = get_browser_binary_location(browser)
  File "open-supreme/env/lib/python3.8/site-packages/harvester/browser.py", line 83, in get_browser_binary_location
    return registry.get(platform.system())[browser]()
TypeError: 'NoneType' object is not subscriptable
````
But i have google chrome, What am I doing wrong?

**Comment by 1fge** [comment]
Hi. Are you running this on Mac OS or Linux?

**Comment by Alymbekov** [comment]
> Hi. Are you running this on Mac OS or Linux?

Running with linux Ubuntu

**Comment by 1fge** [comment]
Unfortunately, the Captcha harvester library this project uses doesn't support Linux. I'll make sure to add a note about this to the README
