### ISSUE TITLE
Hi, I love the project but i get that error

### ISSUE THREAD

**Issue by KatzeMau** [1fge/open-supreme#5]
mac@MacBook-Pro open-supreme % python osp.py
Traceback (most recent call last):
  File "osp.py", line 5, in <module>
    from opensupreme import run_all
  File "/Users/abc/open-supreme/opensupreme/__init__.py", line 1, in <module>
    from .atc_checkout import add_to_cart, checkout
  File "/Users/abc/open-supreme/opensupreme/atc_checkout.py", line 14
    atc_url = f"https://www.supremenewyork.com/shop/{item_id}/add.json"
                                                                      ^
SyntaxError: invalid syntax

**Comment by 1fge** [comment]
Are you using a version of Python higher than 3.6?

**Comment by KatzeMau** [comment]
> Are you using a version of Python higher than 3.6?

I use 3
